#  must be deployed as a deployment | max replication: 3 min replication: 1 CPU percent trigger: 60%
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-app
spec:
  type: ClusterIP
  selector:
    app: api-gateway-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-queue
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z -w 3 rabbit-queue 5672; do echo waiting for queue; sleep 5; done;",
            ]
      containers:
        - name: api-gateway-app
          image: triangle123321/cloud-design-gateway-app:latest
          env:
            - name: GATEWAY_PORT
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: GATEWAY_PORT
            - name: INVENTORY_PORT
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: INVENTORY_PORT
            - name: INVENTORY_HOST
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: INVENTORY_HOST
            - name: QUEUE_PORT
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: QUEUE_PORT
            - name: QUEUE_UNAME
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: QUEUE_UNAME
            - name: QUEUE_PASSW
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: QUEUE_PASSW
            - name: QUEUE_NAME
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: QUEUE_NAME
            - name: QUEUE_HOST
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: QUEUE_HOST
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-app
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
