apiVersion: v1
kind: Service
metadata:
  name: rabbit-queue
spec:
  selector:
    app: rabbit-queue
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit-queue
spec:
  serviceName: "rabbit-queue"
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-queue
  template:
    metadata:
      labels:
        app: rabbit-queue
    spec:
      containers:
        - name: rabbit-queue
          image: triangle123321/cloud-design-queue:v1.0
          env:
            - name: QUEUE_PORT
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: QUEUE_PORT
            - name: QUEUE_UNAME
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: QUEUE_UNAME
            - name: QUEUE_PASSW
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: QUEUE_PASSW
            - name: QUEUE_NAME
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: QUEUE_NAME
            - name: QUEUE_HOST
              valueFrom:
                secretKeyRef:
                  name: cloud-secrets
                  key: QUEUE_HOST
          ports:
            - containerPort: 5672
              protocol: TCP
          volumeMounts:
            - name: rabbit-queue
              mountPath: /var/lib/rabbit-queue/data
  volumeClaimTemplates:
    - metadata:
        name: rabbit-queue
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
        storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-queue-vol
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /mnt/data/rabbit
  claimRef:
    namespace: default
    name: rabbit-queue-rabbit-queue-0